// ═══════════════════════════════════════════════════════════
// GAME DATA
// ═══════════════════════════════════════════════════════════
const SERIES_TONES=[
  {id:'realistic',name:'Near Realistic',refresh:3,stressBonus:0,desc:'Gritty, low-powered. Heroes are tough but mortal.'},
  {id:'dark',name:'Dark & Grim',refresh:4,stressBonus:1,desc:'Street-level noir. Powers are restrained.'},
  {id:'fourcolor',name:'Four Color',refresh:5,stressBonus:2,desc:'Classic superhero action. Bold & bright.'}
];
const SERIES_LEVELS=[
  {id:'gritty',name:'Gritty Realism',baseHP:5,desc:'Minimal powers'},
  {id:'urban',name:'Urban Protectors',baseHP:10,desc:'Street-level heroes'},
  {id:'superheroic',name:'Super-Heroic',baseHP:15,desc:'Standard super-powered'},
  {id:'mightiest',name:"Earth's Mightiest",baseHP:20,desc:'Major league heroes'},
  {id:'offcharts',name:'Off The Charts',baseHP:25,desc:'Cosmic-level power'}
];
const EXP_LEVELS=[
  {id:'normal',name:'Normal Guy in a Super World',skillPts:25,bonusHP:0},
  {id:'new',name:'New/Young Heroes',skillPts:30,bonusHP:2},
  {id:'ropes',name:'Know the Ropes',skillPts:35,bonusHP:5},
  {id:'around',name:'Been Around the Block',skillPts:40,bonusHP:10},
  {id:'highly',name:'Highly Experienced',skillPts:45,bonusHP:15}
];
const SKILLS=['Accuracy','Arcanum','Artificing','Athletics','Contacts','Deceive','Empathy','Fight','Investigate','Knowledge','Leadership','Magic','Mental','Notice','Physique','Power','Provoke','Rapport','Resources','Stealth','Technology','Thief','Treatment','Vehicles','Weapons','Will'];
const CONTROLLING_SKILLS=['Magic','Mental','Power'];
const SKILL_DESC={
Accuracy:'Ranged attacks, throwing, and hitting your mark at a distance.',
Arcanum:'Knowledge of the mystical, extradimensional entities, and ancient rituals.',
Artificing:'Creating and destroying mystical artifacts and enchanted objects.',
Athletics:'General physical fitness, running, jumping, climbing, and dodging.',
Contacts:'Knowing the right people in the right places for information.',
Magic:'Controlling skill for arcane / mystical powers.',
Mental:'Controlling skill for psychic / mental powers.',
Power:'Controlling skill for traditional powers (mutation, accident of birth, technology).',
Deceive:'Lying, misdirection, disguises, and creating false impressions.',
Empathy:'Reading emotions, spotting mood changes, and understanding people.',
Fight:'All forms of unarmed and close-quarters melee combat.',
Investigate:'Finding things through concentrated effort, scrutiny, and analysis.',
Knowledge:'Academic and specialized information across various fields.',
Leadership:'Commanding others, devising tactics, and inspiring allies.',
Notice:'Perception, spotting details at a glance, and general awareness.',
Physique:'Raw physical strength, endurance, and toughness.',
Provoke:'Intimidation, getting a rise out of people, and eliciting negative emotion.',
Rapport:'Making positive connections, being liked and trusted, persuasion.',
Resources:'Material wealth and the ability to acquire things.',
Stealth:'Avoiding detection, hiding, and moving unseen.',
Technology:'Understanding and working with modern tech, vehicles, and devices.',
Thief:'Picking locks, breaking into places, stealing, and bypassing security.',
Treatment:'Medical care, first aid, emergency surgery, and diagnosing injuries.',
Vehicles:'Operating cars, motorcycles, boats, aircraft, and other vehicles.',
Weapons:'Fighting with swords, shields, batons, staves, and other melee weapons.',
Will:'Mental fortitude, resisting mental attacks, and concentration.'
};
const SAMPLE_COLUMNS={
25:[
  {label:'Focused Expert',tiers:{5:1,4:1,3:2,2:3,1:4}},
  {label:'Skilled Specialist',tiers:{4:1,3:3,2:3,1:6}},
  {label:'Well-Rounded',tiers:{3:3,2:3,1:10}},
  {label:'Broad Generalist',tiers:{3:2,2:3,1:13}}
],
30:[
  {label:'Focused Expert',tiers:{5:1,4:2,3:2,2:3,1:5}},
  {label:'Skilled Specialist',tiers:{4:2,3:3,2:3,1:7}},
  {label:'Well-Rounded',tiers:{4:1,3:3,2:4,1:9}},
  {label:'Broad Generalist',tiers:{3:3,2:4,1:13}}
],
35:[
  {label:'Focused Expert',tiers:{5:2,4:2,3:2,2:3,1:5}},
  {label:'Skilled Specialist',tiers:{5:1,4:2,3:3,2:4,1:5}},
  {label:'Well-Rounded',tiers:{4:3,3:3,2:3,1:8}},
  {label:'Broad Generalist',tiers:{4:2,3:3,2:3,1:12}}
],
40:[
  {label:'Focused Expert',tiers:{6:1,5:2,4:2,3:2,2:3,1:4}},
  {label:'Skilled Specialist',tiers:{5:2,4:2,3:3,2:4,1:5}},
  {label:'Well-Rounded',tiers:{5:1,4:2,3:4,2:4,1:7}},
  {label:'Broad Generalist',tiers:{4:2,3:4,2:6,1:8}}
],
45:[
  {label:'Focused Expert',tiers:{6:2,5:2,4:2,3:2,2:3,1:3}},
  {label:'Skilled Specialist',tiers:{6:1,5:2,4:2,3:3,2:4,1:4}},
  {label:'Well-Rounded',tiers:{5:2,4:3,3:3,2:4,1:6}},
  {label:'Broad Generalist',tiers:{5:1,4:3,3:3,2:6,1:7}}
]
};
const ARCHETYPES=[
 {name:'Shadow Operative',tag:'Silent infiltration and lethal precision',shape:'Focused Expert',skills:['Stealth','Fight','Athletics','Weapons','Notice','Accuracy','Deceive','Thief','Physique','Provoke','Will','Empathy','Investigate','Contacts','Vehicles','Treatment','Rapport','Knowledge']},
 {name:'Dark Detective',tag:'World-class investigator and brawler',shape:'Skilled Specialist',skills:['Fight','Investigate','Athletics','Notice','Stealth','Will','Physique','Provoke','Deceive','Technology','Knowledge','Contacts','Empathy','Accuracy','Weapons','Resources','Vehicles','Thief']},
 {name:'Billionaire Inventor',tag:'Genius tech, deep pockets, powered suit',shape:'Skilled Specialist',skills:['Technology','Power','Resources','Knowledge','Accuracy','Contacts','Will','Notice','Leadership','Rapport','Investigate','Deceive','Vehicles','Physique','Athletics','Provoke','Empathy','Fight']},
 {name:'Sentinel Leader',tag:'Inspiring tactician who leads from the front',shape:'Well-Rounded',skills:['Leadership','Fight','Athletics','Will','Physique','Rapport','Notice','Weapons','Empathy','Provoke','Contacts','Investigate','Vehicles','Accuracy','Deceive','Stealth','Knowledge','Treatment']},
 {name:'Living Powerhouse',tag:'Raw strength and unstoppable durability',shape:'Focused Expert',skills:['Physique','Fight','Power','Athletics','Provoke','Will','Notice','Weapons','Empathy','Contacts','Accuracy','Vehicles','Stealth','Rapport','Investigate','Leadership']},
 {name:'Sorcerer Supreme',tag:'Master of arcane forces and rituals',shape:'Skilled Specialist',skills:['Magic','Arcanum','Will','Artificing','Knowledge','Notice','Empathy','Investigate','Rapport','Deceive','Contacts','Provoke','Athletics','Physique','Treatment','Fight','Leadership','Resources']},
 {name:'Psychic',tag:'Telepathy, telekinesis, and iron will',shape:'Skilled Specialist',skills:['Mental','Will','Empathy','Notice','Rapport','Investigate','Knowledge','Provoke','Deceive','Leadership','Contacts','Athletics','Physique','Treatment','Fight','Stealth','Resources','Accuracy']},
 {name:'Amazing Acrobat',tag:'Agile powered brawler in constant motion',shape:'Well-Rounded',skills:['Athletics','Fight','Notice','Power','Accuracy','Will','Physique','Stealth','Provoke','Empathy','Investigate','Technology','Knowledge','Rapport','Contacts','Deceive','Vehicles','Weapons']},
 {name:'Master Marksman',tag:'Deadly aim, gadgets, and field skills',shape:'Skilled Specialist',skills:['Accuracy','Athletics','Notice','Weapons','Stealth','Fight','Physique','Technology','Investigate','Will','Resources','Contacts','Vehicles','Deceive','Provoke','Empathy','Leadership','Treatment']},
 {name:'Charismatic Face',tag:'Spy and socialite who wins with words',shape:'Broad Generalist',skills:['Rapport','Deceive','Empathy','Contacts','Provoke','Notice','Will','Investigate','Resources','Leadership','Stealth','Fight','Athletics','Knowledge','Vehicles','Accuracy','Weapons','Treatment','Physique','Thief']}
];
const SAMPLE_STUNTS=[
{name:'Any Object is a Bullet',skill:'Accuracy',cost:1,desc:'Declare any small object as a ranged weapon when thrown. Weapon: 2 rating.'},
{name:'Lead Rain',skill:'Accuracy',cost:1,desc:'With full-auto weapon success, create Fair (+2) movement opposition in zone until next turn.'},
{name:'Quick Draw',skill:'Accuracy',cost:1,desc:'Use Accuracy instead of Notice for turn order in shooting conflicts.'},
{name:'Ricochet Expert',skill:'Accuracy',cost:1,desc:'Bounce attacks off surfaces to strike targets. Twice per conflict.'},
{name:'Superior Marksman',skill:'Accuracy',cost:1,desc:'Extra free invocation when placing an aspect by taking aim with style.'},
{name:'Trick Shot',skill:'Accuracy',cost:1,desc:'+2 when using ranged weapon to create a Situation Aspect for a fancy shot.'},
{name:'Fortune Telling',skill:'Arcanum',cost:1,desc:'Once per Issue, make a prediction via Create an Advantage.'},
{name:'Hypnotic Voice',skill:'Arcanum',cost:1,desc:'After calm conversation, use Arcanum instead of Rapport or Deceive.'},
{name:'Sixth Sense',skill:'Arcanum',cost:1,desc:'Use Arcanum instead of Notice for mystical/sorcerous things.'},
{name:'Powerful Sixth Sense',skill:'Arcanum',cost:1,desc:'+2 when using Arcanum to discover aspects. Requires Sixth Sense.'},
{name:'A Kind of Magic',skill:'Artificing',cost:1,desc:'Free invocation of artifact aspect when you succeed with style creating it.'},
{name:'Master Artificer',skill:'Artificing',cost:1,desc:'Ignore first 2 points of opposition increase for artifact quality above workshop.'},
{name:'Dazing Counter',skill:'Athletics',cost:1,desc:'On defend with style vs Fight, attach Dazed aspect to opponent with free invoke.'},
{name:'Fluid Technique',skill:'Athletics',cost:1,desc:'Use Athletics instead of Fight to attack and defend in melee.'},
{name:'Uncanny Agility',skill:'Athletics',cost:1,desc:'+2 to Athletics Defend actions when dodging ranged attacks.'},
{name:'Superhuman Agility',skill:'Athletics',cost:1,desc:'+4 to Defend actions for dodging. Requires Uncanny Agility.'},
{name:'Big Man',skill:'Contacts',cost:1,desc:'Pick a field (Criminal, Business, etc). Use Contacts instead of Resources in that field.'},
{name:'Talk the Talk',skill:'Contacts',cost:1,desc:'+2 to Rapport with your field, or use Contacts instead. Requires Big Man.'},
{name:'In the Know',skill:'Contacts',cost:1,desc:'+2 when using Contacts to create a Situation Aspect against someone.'},
{name:'Word on the Street',skill:'Contacts',cost:1,desc:'Once per issue, roll Contacts vs Fair (+2) for crime/plot info.'},
{name:'Power Stunt Expert',skill:'Controlling',cost:1,desc:'+2 bonus when performing Power Stunts.'},
{name:'Power Stunt Mastery',skill:'Controlling',cost:1,desc:'+4 to Power Stunts. Requires Power Stunt Expert.'},
{name:'Actor',skill:'Deceive',cost:1,desc:'Use Deceive instead of Rapport when charming through a situation.'},
{name:'Impersonator',skill:'Deceive',cost:1,desc:'Easily imitate mannerisms and voice; removes cause for disguise examination.'},
{name:'Master of Disguise',skill:'Deceive',cost:1,desc:'+2 to Deceive to prevent someone seeing through your disguise.'},
{name:'Counselor',skill:'Empathy',cost:1,desc:'+2 to Empathy when reducing Mental Consequences in others.'},
{name:'Emotional Trigger',skill:'Empathy',cost:1,desc:'Use Empathy instead of Provoke to intimidate or anger.'},
{name:'Empathic Read',skill:'Empathy',cost:1,desc:'After observation, roll vs Fair (+2) to discover target aspects.'},
{name:'Lie Detector',skill:'Empathy',cost:1,desc:'+2 to all Empathy rolls to detect lies.'},
{name:'Into the Fray',skill:'Fight',cost:1,desc:'Extra Shift of damage when outnumbered in a fight.'},
{name:'Everywhere at Once',skill:'Fight',cost:1,desc:'+2 to Fight when facing 2+ opponents. Requires Into the Fray.'},
{name:'One-Man Army',skill:'Fight',cost:1,desc:'Opponents get no bonus for outnumbering you. Requires Everywhere at Once.'},
{name:'Attention to Detail',skill:'Investigate',cost:1,desc:'Use Investigate instead of Empathy to defend against Deceive.'},
{name:'Eavesdropper',skill:'Investigate',cost:1,desc:'On success eavesdropping, discover or create one additional aspect.'},
{name:'Focused Senses',skill:'Investigate',cost:1,desc:'+2 to Investigation actions when focused on one sense.'},
{name:'Specialist',skill:'Knowledge',cost:1,desc:'+2 to Knowledge in your chosen field. Can take multiple times.'},
{name:'Know It All',skill:'Knowledge',cost:1,desc:'Extra free invocation on Knowledge aspects in your specialty. Requires Specialist.'},
{name:'Mad Scientist',skill:'Knowledge',cost:1,desc:'Use Knowledge instead of Technology in your field. Requires Specialist.'},
{name:'Tactician',skill:'Leadership',cost:1,desc:'+2 to creating situation aspects after studying opponent for 1 minute.'},
{name:'Master Tactician',skill:'Leadership',cost:1,desc:'+2 to Create Advantage after just 1 exchange. Requires Tactician.'},
{name:'Organizational Funding',skill:'Leadership',cost:1,desc:'Use higher of Leadership or Resources for organization funds.'},
{name:'Body Language Reader',skill:'Notice',cost:1,desc:'Use Notice in place of Empathy to learn aspects through observation.'},
{name:'Situational Reflexes',skill:'Notice',cost:1,desc:'Spend a fate point to go first in any exchange regardless of initiative.'},
{name:'Thought Equals Action',skill:'Notice',cost:1,desc:'+2 to Notice for determining initiative; breaks ties.'},
{name:'Face the Pain',skill:'Physique',cost:1,desc:'Once per scene, spend a fate point to clear your 1-Stress or 2-Stress box.'},
{name:'Take the Blow',skill:'Physique',cost:1,desc:'Use Physique to defend against Fight and Weapons attacks.'},
{name:'Tough as Nails',skill:'Physique',cost:1,desc:'Once per scene, spend a fate point to reduce moderate consequence to mild, or erase mild.'},
{name:'Armor of Fear',skill:'Provoke',cost:1,desc:'Roll Provoke vs Will to prevent target from attacking or approaching you.'},
{name:'Intimidating Presence',skill:'Provoke',cost:1,desc:'Use Provoke in place of Empathy to learn aspects by bullying.'},
{name:'Provoke Violence',skill:'Provoke',cost:1,desc:'When you create advantage with Provoke, use free invoke to become their next target.'},
{name:'Best Foot Forward',skill:'Rapport',cost:1,desc:'Twice per session, upgrade a Rapport boost into a full situation aspect.'},
{name:'Demagogue',skill:'Rapport',cost:1,desc:'+2 to Rapport when delivering an inspiring speech to a crowd.'},
{name:'Popular',skill:'Rapport',cost:1,desc:'In areas where you\'re popular, use Rapport in place of Contacts.'},
{name:'Smooth Over',skill:'Rapport',cost:1,desc:'+2 to Rapport when calming a situation (if you\'re not the cause).'},
{name:'Grease the Wheels',skill:'Resources',cost:1,desc:'Use Resources instead of Contacts to find people by spreading money around.'},
{name:'Money Talks',skill:'Resources',cost:1,desc:'Use Resources instead of Rapport where wealth displays would help.'},
{name:'Long Term Investment',skill:'Resources',cost:1,desc:'Once per session, +2 to one Resources roll by selling an investment.'},
{name:'Face in the Crowd',skill:'Stealth',cost:1,desc:'+2 to Stealth to blend into a crowd.'},
{name:'Master of Shadows',skill:'Stealth',cost:1,desc:'+2 to Stealth advantage creation in darkness/shadows.'},
{name:'Ninja Vanish',skill:'Stealth',cost:1,desc:'Once per scene, spend fate point to vanish in plain sight.'},
{name:'Slippery Target',skill:'Stealth',cost:1,desc:'In darkness, use Stealth to defend against ranged attacks from 1+ zones away.'},
{name:'Strike from the Shadows',skill:'Stealth',cost:1,desc:'Use Stealth for physical attacks if target is unaware of you.'},
{name:'Power Tech',skill:'Technology',cost:1,desc:'Roll Technology instead of Power skill when using device-based powers.'},
{name:'Master Inventor',skill:'Technology',cost:1,desc:'Device quality above workshop only increases opposition if +3 steps higher.'},
{name:'No Locks are Safe',skill:'Thief',cost:1,desc:'+2 when picking locks, hacking security, or disarming traps.'},
{name:'Professional Thief',skill:'Thief',cost:1,desc:'+2 to heist-related aspects after casing a place for a day.'},
{name:'Doctor',skill:'Treatment',cost:1,desc:'+2 when treating physical consequences in a facility matching consequence severity.'},
{name:'Field Medic',skill:'Treatment',cost:1,desc:'Once per conflict, treat Stress mid-battle by rolling vs total Stress to heal.'},
{name:'Hard to Shake',skill:'Vehicles',cost:1,desc:'+2 to Vehicles when pursuing another vehicle in a chase.'},
{name:'Pedal to the Metal',skill:'Vehicles',cost:1,desc:'Ties in speed-based contests count as successes.'},
{name:'Riposte',skill:'Weapons',cost:1,desc:'On successful melee Defend with Weapons, inflict 1-Stress on attacker.'},
{name:'Turnabout',skill:'Weapons',cost:1,desc:'On Defend with style using Weapons, deal Shifts as damage. Requires Riposte.'},
{name:'Weapon Blur',skill:'Weapons',cost:1,desc:'Use Weapons instead of Deceive when performing a feint.'},
{name:'Arsenal',skill:'Weapons',cost:1,desc:'Begin play with Kevlar armor and four types of guns or melee weapons.'},
{name:'Backup Weapon',skill:'Weapons',cost:1,desc:'Spend fate point when about to be Disarmed to declare a backup weapon.'}
];
const LADDER=[{val:-2,name:'Terrible'},{val:-1,name:'Poor'},{val:0,name:'Mediocre'},{val:1,name:'Average'},{val:2,name:'Fair'},{val:3,name:'Good'},{val:4,name:'Great'},{val:5,name:'Superb'},{val:6,name:'Fantastic'},{val:7,name:'Epic'},{val:8,name:'Legendary'}];
function ladderName(v){return(LADDER.find(l=>l.val===v)||{name:'???'}).name;}
const ASPECT_CATEGORIES=['Life Changing Event','Life Secret','Core Value','Inner Demons','Inner Strength','Flaw','Dark Secret','Relationships','Personal Belief'];

const TEAM_STUNTS=[
  {id:'heroes_assemble',name:'Heroes Assemble',desc:'Once per scene, +1 bonus when invoking a situation aspect created by a teammate.',requires:null},
  {id:'united_we_stand',name:'United We Stand',desc:'Use Heroes Assemble twice per scene.',requires:'heroes_assemble'},
  {id:'brotherhood',name:'Brotherhood',desc:'Team fate point pool = half PC count (round up), resets each session.',requires:'united_we_stand'},
  {id:'iconic',name:'Iconic',desc:'+2 to Rapport for Create an Advantage at social functions.',requires:null},
  {id:'media_liaison',name:'Media Liaison',desc:'+2 to remove Collateral Damage Consequences involving public perception.',requires:null},
  {id:'pr_specialist',name:'Public Relations Specialist',desc:'Mild Collateral Damage Consequences auto-removed at scene end.',requires:'media_liaison'},
  {id:'reserve_member',name:'Reserve Member',desc:'Call reserve members to scene once per issue via fate point.',requires:null},
  {id:'signature_fastball',name:'Signature Fast Ball',desc:'+2 to Accuracy on throwing character\'s roll for Fast Ball maneuver.',requires:null},
  {id:'team_base',name:'Team Base',desc:'Team gains 10 Headquarters Points. Can be taken multiple times.',requires:null},
  {id:'vengeance',name:'Vengeance',desc:'When member Taken Out or Concedes, others clear 2-Stress or one Mild Consequence.',requires:null},
  {id:'ultimate_vengeance',name:'Ultimate Vengeance',desc:'Use Vengeance twice per scene.',requires:'vengeance'}
];
const TEAM_COMPLICATIONS=[
  {id:'corporate_investor',name:'Corporate Investor',desc:'Corporation can demand missions; failure has consequences.'},
  {id:'dark_secret',name:'Dark Secret',desc:'Team committed an act that could end careers if revealed.'},
  {id:'media_animosity',name:'Media Animosity',desc:'Enemy in media increases opposition to clear Collateral Damage by +1.'},
  {id:'unwanted_attention',name:'Unwanted Attention',desc:'A follower/reporter causes constant complications.'}
];

const GENERAL_SE=[
  {id:'advantageous',name:'Advantageous',cost:1,desc:'+2 to create a chosen kind of situation aspect (e.g. Stunned, Dazed); pick the aspect type when bought.'},
  {id:'area_effect',name:'Area Effect',cost:1,desc:'Hit everyone in the same zone without splitting your roll. Each extra purchase adds another zone.'},
  {id:'charge_object',name:'Charge Object',cost:1,desc:'Touch an object to charge it; whoever contacts it later triggers the Blast (uses Accuracy at touch range).'},
  {id:'concussive_g',name:'Concussive',cost:1,desc:'For each Weapon Rating you reduce damage by, knock the target back two zones instead of one.'},
  {id:'countering',name:'Countering / Nullify Resistance',cost:1,desc:'+2 to the opposition for anyone trying to counter or nullify this power.'},
  {id:'dangerous',name:'Dangerous',cost:2,desc:'Once per scene, spend a fate point on a hit to force a Moderate Consequence instead of stress.'},
  {id:'deadly',name:'Deadly',cost:1,desc:'Once per issue, spend a fate point on a hit to deal both stress AND a Consequence of equal value.'},
  {id:'demolishing',name:'Demolishing',cost:1,desc:'Doubles this power’s Material Strength reduction when destroying objects.'},
  {id:'durable',name:'Durable',cost:1,desc:'Once per scene, spend a fate point to absorb a Mild Consequence (Potent/Deadly/Lethal hits give the FP back).'},
  {id:'encasing',name:'Encasing',cost:1,desc:'On success-with-style, lower damage to encase the target; passive opposition to escape equals damage transferred.'},
  {id:'entangling',name:'Entangling',cost:1,desc:'+2 to grapple with this power. Target breaks free with an Overcome equal to your grapple Shifts.'},
  {id:'extended_range',name:'Extended Range',cost:1,desc:'For each Weapon Rating you reduce damage by, extend the attack’s range by one zone.'},
  {id:'follow_up',name:'Follow-Up',cost:1,desc:'On success-with-style, place a Boost on the target without lowering your damage.'},
  {id:'gaseous',name:'Gaseous',cost:1,desc:'Damaging power becomes a slow-fill gas cloud (3 exchanges to fill a zone) attacking everyone inside each turn.'},
  {id:'ghostly',name:'Ghostly',cost:1,desc:'The power normally affects astral and intangible targets.'},
  {id:'hard_hitting',name:'Hard Hitting',cost:1,desc:'Once per issue, spend a fate point to bump a Consequence you forced one severity higher.'},
  {id:'homing',name:'Homing',cost:2,desc:'On a miss, the Blast keeps re-attacking each turn (max = power level) until it hits or a Defend succeeds with style.'},
  {id:'indirect',name:'Indirect',cost:1,desc:'Attack originates somewhere else; ignores cover/obstacle aspects (does not bypass Forcefields).'},
  {id:'lethal',name:'Lethal',cost:3,desc:'Once per scene, spend a fate point on a hit to force a Severe Consequence instead of stress.'},
  {id:'mega_attack',name:'Mega-Attack',cost:2,desc:'Once per issue, double the Weapon Rating for one attack. Power then shuts down for the scene; you also take stress equal to levels added.'},
  {id:'multi_targeting',name:'Multi-Targeting',cost:2,desc:'On an area attack, you don’t split your result and may exclude targets you choose. Includes Area Effect.'},
  {id:'penetrating',name:'Penetrating',cost:2,desc:'On success-with-style, spend a fate point to ignore Imperviousness and bypass 2 levels of Invulnerability (3 if not Impervious).'},
  {id:'persistent',name:'Persistent',cost:3,desc:'Once per scene, spend a fate point so an attack that caused a Consequence keeps attacking each turn until Defended.'},
  {id:'potent',name:'Potent',cost:1,desc:'Once per scene, spend a fate point on a hit to force a Mild Consequence instead of stress.'},
  {id:'power_stress',name:'Power Stress',cost:1,desc:'Once per scene, spend a fate point to lower your power levels (across one or more powers) instead of taking stress.'},
  {id:'reinforced',name:'Reinforced',cost:3,desc:'Once per scene, spend a fate point to absorb a Severe Consequence (Potent/Deadly/Lethal hits give the FP back).'},
  {id:'reroute_power',name:'Reroute Power',cost:1,desc:'Once per scene, spend a fate point to shift levels between powers (e.g. -2 Force Field, +2 Blast). Reverts at scene end.'},
  {id:'set_up',name:'Set-Up',cost:1,desc:'On success-with-style, lowering damage to place a boost grants a situation aspect with a free invocation instead.'},
  {id:'tough',name:'Tough',cost:2,desc:'Once per scene, spend a fate point to absorb a Moderate Consequence (Potent/Deadly/Lethal hits give the FP back).'},
  {id:'trans_dimensional',name:'Trans-Dimensional',cost:1,desc:'Power affects targets in another dimension as if you were there. One extra dimension per purchase.'},
  {id:'unnoticeable',name:'Unnoticeable',cost:1,desc:'The power is invisible to the naked eye — hard to tell where it’s coming from by sight.'},
  {id:'useable_on_others',name:'Useable on Others',cost:1,desc:'A self-only power (e.g. Invulnerability) can be applied to others by touch (Fair (+2) opposition).'},
  {id:'volley',name:'Volley',cost:1,desc:'Power fires a rapid volley; +1 to the attack roll.'}
];
const GENERAL_LIMITS=[
  {id:'always_on',name:'Always On',cost:-1,desc:'The power can’t be turned off. If negated, it auto-reactivates when nullification ends.'},
  {id:'no_stunts',name:'Cannot Use Power Stunts',cost:-1,desc:'The power can’t be modified using Power Stunts.'},
  {id:'damaging_l',name:'Damaging',cost:-1,desc:'Each exchange you use the power, you take 2-Stress; Invulnerability does not reduce it.'},
  {id:'distracting',name:'Distracting',cost:-1,desc:'Using the power leaves you off-balance — attacks against you gain +2.'},
  {id:'fatiguing',name:'Fatiguing',cost:-1,desc:'Each use causes 2-Stress; can be resisted by spending a fate point. Invulnerability does not help.'},
  {id:'grappling',name:'Grappling Attack',cost:-1,desc:'You must successfully grapple a target before this power can attack them.'},
  {id:'longer_activation',name:'Longer Activation',cost:-1,desc:'The power activates only every other exchange instead of every exchange.'},
  {id:'reduced_range',name:'Reduced Range',cost:-1,desc:'Each time taken, the power’s range is reduced by 2 zones.'},
  {id:'restricted',name:'Restricted',cost:-1,desc:'Power is limited to certain situations or targets (e.g. only on objects, only on living beings, requires chanting, etc.).'},
  {id:'sense_reliant',name:'Sense Reliant',cost:-1,desc:'Power requires the target be sensed (sight, hearing, touch, etc.). Pick the sense when taken.'},
  {id:'unstable',name:'Unstable',cost:-3,desc:'Roll the dice when used: 0 to +4 works; -1 to -3 fails; -4 burns out for the scene.'},
  {id:'wild_power',name:'Wild Power',cost:-3,desc:'The power’s timing and effects are under GM control rather than the hero’s.'}
];

const POWERS=[
{id:'absorption',name:'Absorption',cost:'2,4,6',flat:false,levels:[2,4,6],skill:'None',desc:'Absorb energy or kinetic damage, gain bonus to Attack/Overcome.',se:[{name:'Absorption Healing',cost:2,desc:'Use absorbed hits to heal stress'},{name:'Accumulate Energy',cost:2,desc:'Store energy for extra turns'},{name:'Energy Sponge',cost:1,desc:'Absorb ambient energy'},{name:'Power Boost',cost:3,desc:'Channel into other powers'}],lim:[{name:'Living Bomb',cost:-1,desc:'Exploding energy damages self and zone'},{name:'Requires Block',cost:-1,desc:'Must Defend to absorb'},{name:'Self-Damaging',cost:-1,desc:'Takes stress when absorbing'},{name:'Specific Energy',cost:-1,desc:'Only one energy type'}],levelDesc:{2:'Negate 4-Hits; +2 Attack/Overcome',4:'Negate 8-Hits; +4 Attack/Overcome',6:'Negate 12-Hits; +6 Attack/Overcome'}},
{id:'adoptive_muscle',name:'Adoptive Muscle Memory',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Mimic fighting ability of observed targets.',se:[{name:'Advanced Memory',cost:1,desc:'Copy complex abilities'},{name:'Rapid Power',cost:1,desc:'Activate as free action'}],lim:[]},
{id:'adrenaline_surge',name:'Adrenaline Surge',cost:'1',flat:true,levels:[1],skill:'Will',desc:'Gain cumulative +1 to a chosen skill per exchange (max +4).',se:[{name:'Additional Skill',cost:1,desc:'Apply to one more skill'},{name:'Rapid Power',cost:1,desc:'Activate as free action'}],lim:[]},
{id:'affliction',name:'Affliction',cost:'7',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Infect targets with disease/poison; opposed vs Physique/Will.',se:[],lim:[]},
{id:'air_control',name:'Air Control',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control air and winds; +2 creating wind aspects.',se:[{name:'Ultimate Control',cost:1,desc:'Greater mastery'},{name:'Rapid Power',cost:1,desc:'Activate as free action'}],lim:[]},
{id:'animal_control',name:'Animal Control',cost:'4',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control nearby animals; summon ranks based on Shifts.',se:[{name:'Ready to Rumble',cost:1,desc:'Animals act immediately'},{name:'Swarm',cost:2,desc:'Control a swarm'}],lim:[]},
{id:'animal_mimicry',name:'Animal Mimicry',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Mimic one animal\'s abilities; gain temporary aspects.',se:[{name:'Menagerie',cost:1,desc:'Mimic multiple animals'},{name:'Rapid Power',cost:1,desc:'Free action'}],lim:[]},
{id:'animate',name:'Animate',cost:'5',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Bring inanimate objects to life.',se:[{name:'Ready to Rumble',cost:1,desc:'Animations act immediately'}],lim:[]},
{id:'armory_summoning',name:'Armory Summoning',cost:'4',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Summon weapons/armor; Shifts determine Rating.',se:[{name:'Dual Weapons',cost:1,desc:'Two weapons at once'},{name:'Rapid Power',cost:1,desc:'Free action'}],lim:[]},
{id:'astral_projection',name:'Astral Projection',cost:'1',flat:true,levels:[1],skill:'None',desc:'Separate astral form; pass through barriers; immune to physical.',se:[],lim:[]},
{id:'aura',name:'Aura',cost:'3',flat:true,levels:[1],skill:'None',desc:'Damaging field; attackers take 2-Hits on your Defend success.',se:[{name:'Intense Aura',cost:1,desc:'+2 Defend vs ranged attacks the aura would protect against (e.g. ice aura vs bullets, energy aura vs energy attacks).'}],lim:[]},
{id:'blast',name:'Blast',cost:'1-6',flat:false,levels:[1,2,3,4,5,6],skill:'Accuracy',desc:'Ranged attack; Weapon Rating equal to power level.',levelDesc:{1:'Weapon 1; range 2 zones',2:'Weapon 2; range 3 zones',3:'Weapon 3; range 4 zones',4:'Weapon 4; range 5 zones',5:'Weapon 5; range 6 zones',6:'Weapon 6; range 7 zones'},se:[{name:'Concussive Blast',cost:2,desc:'Knockback on hit'},{name:'Corrosive',cost:2,desc:'Eats through defenses'},{name:'Electrical',cost:2,desc:'Can stun'},{name:'Energy',cost:1,desc:'Generic energy'},{name:'Fire',cost:3,desc:'Sets targets on fire'},{name:'Ice',cost:1,desc:'Can slow'},{name:'Radiation',cost:2,desc:'Radiation damage'},{name:'Sonic',cost:2,desc:'Sound-based'}],lim:[{name:'Short Range',cost:-1,desc:'Reduced range'},{name:'Obvious',cost:-1,desc:'Highly visible'}]},
{id:'boost',name:'Boost',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Temporarily increase another\'s skill +2 or +4.',se:[],lim:[{name:'Overload',cost:-1,desc:'Target takes stress after'},{name:'Single Skill',cost:-1,desc:'Only one skill'}]},
{id:'burrowing',name:'Burrowing',cost:'2',flat:true,levels:[1],skill:'None',desc:'Move underground; +2 when erupting.',se:[],lim:[]},
{id:'chameleon',name:'Chameleon',cost:'2',flat:true,levels:[1],skill:'None',desc:'Alter appearance/voice to resemble any living being.',se:[{name:'Near Perfect Form',cost:1,desc:'Almost undetectable'}],lim:[]},
{id:'cold_control',name:'Cold Control',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control cold; create ice constructs; +2 cold aspects.',se:[{name:'Intense Cold',cost:1,desc:'Extreme freezing'},{name:'Sub-arctic',cost:1,desc:'Sub-zero conditions'}],lim:[]},
{id:'darkness_control',name:'Darkness Control',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control darkness; extinguish light; immune to darkness.',se:[{name:'Hungering Darkness',cost:1,desc:'Spend a free invoke from a darkness aspect to instill fear (opposed by Will). Affected targets suffer +2 opposition on all rolls inside the darkness.'}],lim:[]},
{id:'death_speak',name:'Death Speak',cost:'1',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Communicate with spirits by touching a corpse.',se:[],lim:[]},
{id:'deflection',name:'Deflection',cost:'2',flat:true,levels:[1],skill:'Fight/Weapons',desc:'Deflect ranged attacks; reflect half damage on success with style.',se:[{name:'Full Deflection',cost:1,desc:'Reflect full damage'}],lim:[]},
{id:'density',name:'Density',cost:'2,4,6',flat:false,levels:[2,4,6],skill:'None',desc:'Increase mass; each level +2 Physique, -2 Athletics.',se:[],lim:[],levelDesc:{2:'+2 Physique, -2 Athletics',4:'+4 Physique, -4 Athletics',6:'+6 Physique, Athletics min -2'}},
{id:'dimensional_pocket',name:'Dimensional Pocket',cost:'1',flat:true,levels:[1],skill:'None',desc:'Private dimensional storage space.',se:[{name:'Lord of the Domain',cost:1,desc:'Full control over pocket'}],lim:[]},
{id:'dimensional_travel',name:'Dimensional Travel',cost:'1',flat:true,levels:[1],skill:'None',desc:'Travel between known dimensions freely.',se:[],lim:[]},
{id:'drain',name:'Drain',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Lower target\'s skill -2 or -4 steps.',se:[{name:'Transference',cost:2,desc:'Gain what you drain'}],lim:[{name:'Single Skill',cost:-1,desc:'Only drain one skill'}]},
{id:'dream_control',name:'Dream Control',cost:'1',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Enter others\' dreams; opposed vs Will.',se:[],lim:[]},
{id:'duplication',name:'Duplication',cost:'5',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Create exact copies of self with all powers except Duplication.',se:[{name:'Damage Soaking',cost:3,desc:'Duplicates absorb damage'},{name:'Ready to Rumble',cost:1,desc:'Act immediately'},{name:'Sacrificial Lamb',cost:2,desc:'Destroy duplicate to avoid consequence'},{name:'Horde',cost:2,desc:'Create many more'}],lim:[{name:'Shared Damage',cost:-1,desc:'Damage affects you'},{name:'Psychic Feedback',cost:-1,desc:'Losing duplicates causes mental stress'}]},
{id:'earth_control',name:'Earth Control',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control earth; create barriers; encase targets.',se:[],lim:[]},
{id:'electrical_control',name:'Electrical Control',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control electricity; power/disable devices.',se:[],lim:[]},
{id:'emotion_control',name:'Emotion Control',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Alter emotional state via situation aspects; +2 placing.',se:[],lim:[]},
{id:'empower',name:'Empower',cost:'4',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Imbue others with powers up to controlling skill rank.',se:[],lim:[]},
{id:'esp',name:'ESP',cost:'1',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Remotely sense other locations.',se:[],lim:[]},
{id:'extraordinary_intellect',name:'Extraordinary Intellect',cost:'1',flat:true,levels:[1],skill:'None',desc:'Declare story details once per scene from vast knowledge.',se:[],lim:[]},
{id:'extra_limbs',name:'Extra Limbs',cost:'1',flat:true,levels:[1],skill:'None',desc:'Additional limbs for grappling and multi-tasking.',se:[],lim:[]},
{id:'fire_control',name:'Fire Control',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control fire/heat; +2 creating fire aspects.',se:[{name:'Living Flame',cost:3,desc:'Animate an existing fire (Overcome action). It acts independently with attack skill = Shifts gained, 2 stress and 1 Mild Consequence.'}],lim:[]},
{id:'flight',name:'Flight',cost:'1-4',flat:false,levels:[1,2,3,4],skill:'None',desc:'Fly through the air. Higher levels = faster.',se:[],lim:[],levelDesc:{1:'Gliding; Speed 2; move 4 zones/turn',2:'Fast cars speed; Speed 3; move 6 zones/turn',3:'Helicopter/small plane; Speed 4; move to any zone',4:'Escape velocity; Speed 5; spend FP to arrive at any scene'}},
{id:'force_control',name:'Force Control',cost:'3',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Generate energy constructs; use as Super-Strength for grappling.',se:[{name:'Battering Ram',cost:1,desc:'Focused force attack'},{name:'Expanded Field',cost:1,desc:'Affect larger area'}],lim:[]},
{id:'forcefield',name:'Forcefield',cost:'1-6',flat:false,levels:[1,2,3,4,5,6],skill:'Magic/Mental/Power',desc:'Defensive field; controlling skill + level as attack opposition.',se:[],lim:[],levelDesc:{1:'Skill +1 vs attacks',2:'Skill +2 vs attacks',3:'Skill +3 vs attacks',4:'Skill +4 vs attacks',5:'Skill +5 vs attacks',6:'Skill +6 vs attacks'}},
{id:'friction_control',name:'Friction Control',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Create slippery or sticky situation aspects.',se:[],lim:[]},
{id:'gravity_control',name:'Gravity Control',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Reduce or increase gravitational pull.',se:[{name:'Intense Gravity',cost:1,desc:'Extreme force'}],lim:[]},
{id:'growth',name:'Growth',cost:'2-12',flat:false,levels:[2,4,6,8,10,12],skill:'None',desc:'Grow immense; gain Super-Strength equal to level.',se:[{name:'Regrowth',cost:1,desc:'Regenerate while giant'}],lim:[],levelDesc:{2:'40ft; Super-Str 2; Density 1',4:'75ft; Super-Str 4; Density 2',6:'100ft+; Super-Str 6; Density 3',8:'Colossal; Super-Str 8; Density 4',10:'Titanic; Super-Str 10; Density 5',12:'Mountainous; Super-Str 12; Density 6'}},
{id:'hardiness',name:'Hardiness',cost:'1-6',flat:false,levels:[1,2,3,4,5,6],skill:'None',desc:'Each level adds a Stress box or Consequence slot.',se:[],lim:[],levelDesc:{1:'Additional Stress Box',2:'Additional Mild Consequence Slot',3:'Additional Stress Box',4:'Additional Moderate Consequence Slot',5:'Additional Stress Box',6:'Additional Severe Consequence Slot'}},
{id:'healing',name:'Healing',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Heal Stress and Consequences of others.',se:[{name:'Regrowth',cost:1,desc:'Regrow limbs'},{name:'Restoration',cost:1,desc:'Cure diseases'},{name:'Resurrection',cost:1,desc:'Raise the dead'}],lim:[]},
{id:'hyper_action',name:'Hyper-Action',cost:'1',flat:true,levels:[1],skill:'None',desc:'Complete tasks in less time; -4 steps on Time chart.',se:[],lim:[]},
{id:'hyper_movement',name:'Hyper-Movement',cost:'1',flat:true,levels:[1],skill:'None',desc:'Unique movement: air walking, wall-crawling, water walking, etc.',se:[],lim:[]},
{id:'hyper_sense',name:'Hyper-Sense',cost:'1',flat:true,levels:[1],skill:'None',desc:'Enhanced senses: danger sense, x-ray vision, telescopic, etc.',se:[],lim:[]},
{id:'illusion',name:'Illusion',cost:'3',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Create visual illusions; targets roll Will to disbelieve.',se:[],lim:[]},
{id:'immoveable',name:'Immoveable',cost:'2',flat:true,levels:[1],skill:'None',desc:'Cannot be moved; +2 Defend against knockback.',se:[],lim:[]},
{id:'immunity',name:'Immunity',cost:'1,3,5',flat:false,levels:[1,3,5],skill:'None',desc:'Immune to specific damage types or conditions.',se:[],lim:[]},
{id:'intangible',name:'Intangible',cost:'3',flat:true,levels:[1],skill:'None',desc:'Pass through solid objects; immune to physical attacks.',se:[],lim:[]},
{id:'interface',name:'Interface',cost:'1',flat:true,levels:[1],skill:'None',desc:'Mentally interface with technology.',se:[],lim:[]},
{id:'invisibility',name:'Invisibility',cost:'2-6',flat:false,levels:[2,3,4,5,6],skill:'None',desc:'Become invisible; higher levels = harder to detect.',se:[],lim:[]},
{id:'invulnerability',name:'Invulnerability',cost:'1-6',flat:false,levels:[1,2,3,4,5,6],skill:'None',desc:'Reduce damage by 1 per level before Stress.',se:[{name:'Impervious',cost:2,desc:'Ignore attacks below threshold'}],lim:[],levelDesc:{1:'Armor 1',2:'Armor 2',3:'Armor 3',4:'Armor 4',5:'Armor 5',6:'Armor 6'}},
{id:'leaping',name:'Leaping',cost:'1-4',flat:false,levels:[1,2,3,4],skill:'None',desc:'Superhuman jumping; each level increases distance.',se:[],lim:[],levelDesc:{1:'Move 4 zones/turn free, if no barriers',2:'Move 6 zones/turn free, if no barriers',3:'Move 8 zones free; ignore ground-based aspects',4:'Leap to any nearby zone; ignore all ground aspects'}},
{id:'life_support',name:'Life Support',cost:'2',flat:true,levels:[1],skill:'None',desc:'Survive hostile environments without life support.',se:[],lim:[]},
{id:'light_control',name:'Light Control',cost:'1',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control light; create illumination or blindness.',se:[],lim:[]},
{id:'living_seance',name:'Living S\u00e9ance',cost:'1',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Communicate with spirits at a distance.',se:[],lim:[]},
{id:'luck',name:'Luck',cost:'2',flat:true,levels:[1],skill:'None',desc:'Reroll or force reroll once per scene.',se:[],lim:[]},
{id:'magnetic_control',name:'Magnetic Control',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control magnetic fields; attract/repel metal.',se:[],lim:[]},
{id:'matter_control',name:'Matter Control',cost:'3',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control and shape matter; transmute substances.',se:[],lim:[]},
{id:'melee_attack',name:'Melee Attack',cost:'1-6',flat:false,levels:[1,2,3,4,5,6],skill:'Fight/Weapons',desc:'Physical melee; Weapon Rating equal to level.',se:[{name:'Energy Melee',cost:2,desc:'Energy-based melee'}],lim:[],levelDesc:{1:'Weapon 1',2:'Weapon 2',3:'Weapon 3',4:'Weapon 4',5:'Weapon 5',6:'Weapon 6'}},
{id:'memory_augmentation',name:'Memory Augmentation',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Perfect recall; share memories.',se:[],lim:[]},
{id:'mental_blast',name:'Mental Blast',cost:'1-6',flat:false,levels:[1,2,3,4,5,6],skill:'Magic/Mental/Power',desc:'Psychic ranged attack; targets Mental Stress.',se:[],lim:[]},
{id:'mental_invulnerability',name:'Mental Invulnerability',cost:'1-6',flat:false,levels:[1,2,3,4,5,6],skill:'None',desc:'Reduce mental damage by 1 per level.',se:[],lim:[]},
{id:'mind_control',name:'Mind Control',cost:'5',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control another\'s actions; opposed by Will.',se:[],lim:[]},
{id:'mind_probe',name:'Mind Probe',cost:'1',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Read surface thoughts; deeper with Overcome.',se:[],lim:[]},
{id:'mind_switch',name:'Mind Switch',cost:'5',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Switch bodies with target; opposed by Will.',se:[],lim:[]},
{id:'molecular_chameleon',name:'Molecular Chameleon',cost:'3',flat:true,levels:[1],skill:'None',desc:'Take on properties of materials touched.',se:[],lim:[]},
{id:'paralyze',name:'Paralyze',cost:'3',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Paralyze targets; opposed by Will.',se:[],lim:[]},
{id:'plant_control',name:'Plant Control',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control plants; create barriers; entangle.',se:[],lim:[]},
{id:'postcognition',name:'Postcognition',cost:'1',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'See past events; opposition based on age.',se:[],lim:[]},
{id:'power_mimicry',name:'Power Mimicry',cost:'5',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Copy another character\'s powers temporarily.',se:[],lim:[]},
{id:'power_nullify',name:'Power Nullify',cost:'1,3,5',flat:false,levels:[1,3,5],skill:'Magic/Mental/Power',desc:'Nullify powers; opposed vs controlling skill.',se:[],lim:[]},
{id:'precognition',name:'Precognition',cost:'1',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'See future events; vague unless success with style.',se:[],lim:[]},
{id:'psychic_blades',name:'Psychic Blades',cost:'1-6',flat:false,levels:[1,2,3,4,5,6],skill:'Mental',desc:'Mental weapons; targets Mental Stress.',se:[],lim:[]},
{id:'psychic_forcefield',name:'Psychic Forcefield',cost:'1-6',flat:false,levels:[1,2,3,4,5,6],skill:'Magic/Mental/Power',desc:'Mental defense field against psychic attacks.',se:[],lim:[]},
{id:'radiation_control',name:'Radiation Control',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control radiation effects.',se:[],lim:[]},
{id:'regeneration',name:'Regeneration',cost:'4',flat:true,levels:[1],skill:'None',desc:'Auto-heal Stress/Consequences; regrow limbs.',se:[{name:'Self-Destruct',cost:2,desc:'Explode and reform'}],lim:[]},
{id:'sensory_shield',name:'Sensory Shield',cost:'1',flat:true,levels:[1],skill:'None',desc:'Shield senses from overload and sensory attacks.',se:[],lim:[]},
{id:'serial_reincarnation',name:'Serial Reincarnation',cost:'2',flat:true,levels:[1],skill:'None',desc:'Return in a new body with memories when killed.',se:[],lim:[]},
{id:'shapeshift',name:'Shapeshift',cost:'5',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Change into other forms.',se:[],lim:[]},
{id:'shrinking',name:'Shrinking',cost:'1-6',flat:false,levels:[1,2,3,4,5,6],skill:'None',desc:'Reduce size each level.',se:[],lim:[]},
{id:'sicken',name:'Sicken',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Make targets ill; opposed by Physique.',se:[],lim:[]},
{id:'sleep',name:'Sleep',cost:'1',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Put targets to sleep; opposed by Will.',se:[],lim:[]},
{id:'sorcery',name:'Sorcery',cost:'3',flat:true,levels:[1],skill:'Arcanum',desc:'Channel raw arcane magic; flexible casting.',se:[],lim:[]},
{id:'sound_wave_control',name:'Sound Wave Control',cost:'1',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control sound waves; sonic attacks.',se:[],lim:[]},
{id:'spatial_control',name:'Spatial Control',cost:'1',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Manipulate space; create barriers.',se:[],lim:[]},
{id:'spinning',name:'Spinning',cost:'1',flat:true,levels:[1],skill:'None',desc:'Spin rapidly; create whirlwind effects.',se:[],lim:[]},
{id:'stretching',name:'Stretching',cost:'3',flat:true,levels:[1],skill:'None',desc:'Stretch body; ignore zone limits for melee.',se:[],lim:[]},
{id:'summon',name:'Summon',cost:'5',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Summon creatures; Shifts determine ranks.',se:[{name:'Ready to Rumble',cost:1,desc:'Creatures act immediately'}],lim:[]},
{id:'summon_swarm',name:'Summon Swarm',cost:'4',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Summon a swarm of small creatures.',se:[],lim:[]},
{id:'super_speed',name:'Super-Speed',cost:'1-4',flat:false,levels:[1,2,3,4],skill:'Athletics',desc:'Superhuman speed; higher levels = faster.',se:[],lim:[],levelDesc:{1:'Running horse speed; 4 zones/turn; Speed 2',2:'200+ mph; run on walls/water; 6 zones/turn; Speed 3',3:'Match small planes; Speed 4',4:'Supersonic+; any zone free; spend FP to reach any scene; Speed 5'}},
{id:'super_strength',name:'Super-Strength',cost:'1-6',flat:false,levels:[1,2,3,4,5,6],skill:'Physique',desc:'Enhanced might; Weapon Rating equal to level.',se:[],lim:[],levelDesc:{1:'Weapon 1; lift a car',2:'Weapon 2; lift semi trucks',3:'Weapon 3; lift a loaded jet fighter',4:'Weapon 4; heft a small building',5:'Weapon 5; move large buildings',6:'Weapon 6; carry battleships'}},
{id:'swinging',name:'Swinging',cost:'2',flat:true,levels:[1],skill:'None',desc:'Swing via environment; ignore movement restrictions.',se:[],lim:[]},
{id:'telekinesis',name:'Telekinesis',cost:'1',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Move objects mentally.',se:[],lim:[]},
{id:'telepathy',name:'Telepathy',cost:'1',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Communicate mentally; opposed by Will for unwilling.',se:[],lim:[]},
{id:'teleportation',name:'Teleportation',cost:'1-6',flat:false,levels:[1,2,3,4,5,6],skill:'Magic/Mental/Power',desc:'Teleport; range based on power level.',se:[],lim:[{name:'Must See Destination',cost:-1,desc:'Must see target location'}],levelDesc:{1:'A few miles',2:'Several hundred miles',3:'Several thousand miles',4:'Anywhere on the planet',5:'Earth to the moon',6:'Anywhere in same star system'}},
{id:'time_control',name:'Time Control',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Slow or speed time in an area.',se:[],lim:[]},
{id:'time_travel',name:'Time Travel',cost:'1-6',flat:false,levels:[1,2,3,4,5,6],skill:'Magic/Mental/Power',desc:'Travel through time; range extends per level.',se:[],lim:[],levelDesc:{1:'A few minutes',2:'Several hours',3:'Several months',4:'Several years',5:'Several decades',6:'The timestream is your playground'}},
{id:'two_dimensional',name:'Two-Dimensional',cost:'2',flat:true,levels:[1],skill:'None',desc:'Become flat/2D; slip through cracks.',se:[],lim:[]},
{id:'vampirism',name:'Vampirism',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Drain life force; heal with drained energy.',se:[],lim:[]},
{id:'water_control',name:'Water Control',cost:'2',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control water; create waves and constructs.',se:[],lim:[]},
{id:'weather_control',name:'Weather Control',cost:'5',flat:true,levels:[1],skill:'Magic/Mental/Power',desc:'Control weather patterns; create storms.',se:[],lim:[]}
];

// GEAR — mundane items from Chapter 10. Free to carry; not Hero Point cost.
// Devices (super-science) are still built as Power Sets.
const GEAR=[
// Melee weapons
{id:'baton',name:'Baton',cat:'Melee',rating:1,desc:'Basic blunt weapon.'},
{id:'knife',name:'Knife',cat:'Melee',rating:1,desc:'Concealable blade.'},
{id:'rapier',name:'Rapier',cat:'Melee',rating:1,desc:'Light thrusting sword.'},
{id:'short_sword',name:'Short Sword',cat:'Melee',rating:2,desc:'One-handed blade.'},
{id:'long_sword',name:'Long Sword',cat:'Melee',rating:2,desc:'Heavy blade.'},
// Ranged weapons
{id:'pistol_9mm',name:'9mm Pistol',cat:'Ranged',rating:2,range:2,special:['+2 to cover fire']},
{id:'pistol_50',name:'.50 Caliber Pistol',cat:'Ranged',rating:3,range:2,special:[]},
{id:'shotgun',name:'Shotgun',cat:'Ranged',rating:2,range:2,special:[]},
{id:'submachine_gun',name:'Submachine Gun',cat:'Ranged',rating:2,range:1,special:['+2 to cover fire']},
{id:'assault_rifle',name:'Assault Rifle',cat:'Ranged',rating:3,range:2,special:['Armor Penetrating','Dangerous','Long Range (1)']},
{id:'sniper_rifle',name:'Sniper Rifle',cat:'Ranged',rating:4,range:'Far',special:['+1 Aim','Long Range (3)']},
{id:'rocket_launcher',name:'Rocket Launcher',cat:'Ranged',rating:8,range:'Far',special:['Area Effect','Armor Pen (2)','Demolishing','Lethal','Long Range']},
{id:'crossbow',name:'Crossbow',cat:'Ranged',rating:1,range:1,special:[]},
{id:'flamethrower',name:'Flamethrower',cat:'Ranged',rating:2,range:1,special:['Continuous','Potent']},
{id:'net_gun',name:'Net Gun',cat:'Ranged',rating:1,range:1,special:['Entangling']},
// Thrown / explosives
{id:'grenade',name:'Grenade',cat:'Thrown',rating:2,range:'Thrown 2',special:['Area Effect','Dangerous']},
{id:'flashbang',name:'Flashbang',cat:'Thrown',rating:0,range:'Thrown 2',special:['Area Effect','Aspect: Blinded & Deafened']},
{id:'smoke_grenade',name:'Smoke Grenade',cat:'Thrown',rating:0,range:'Thrown 2',special:['Area Effect','Aspect: Choking & Blinded']},
// Armor
{id:'leather_armor',name:'Leather',cat:'Armor',armor:1,desc:'Leather or layered clothing.'},
{id:'kevlar',name:'Kevlar',cat:'Armor',armor:2,desc:'Bulletproof vest.'},
{id:'reinforced_kevlar',name:'Reinforced Kevlar',cat:'Armor',armor:3,special:['Tough'],desc:'Absorb a Moderate consequence (1/scene).'},
{id:'experimental_kevlar',name:'Experimental Kevlar',cat:'Armor',armor:3,special:['Camouflage','Tough'],desc:'Bleeding-edge tactical armor.'},
{id:'platemail',name:'Platemail',cat:'Armor',armor:2,special:['Durable'],desc:'Absorb a Mild consequence (1/scene).'},
// Utility / everyday
{id:'binoculars',name:'Binoculars',cat:'Utility',special:['Telescopic Vision']},
{id:'commlink',name:'Comm-Link',cat:'Utility',special:['Signal-based Telepathy']},
{id:'flashlight',name:'Flashlight',cat:'Utility',special:['Ignores 1 darkness aspect']},
{id:'laptop',name:'Laptop',cat:'Utility',special:['Internet access']},
{id:'lockpicks',name:'Lockpicks',cat:'Utility',special:['+2 to overcome locks']},
{id:'medkit',name:'Medkit',cat:'Utility',special:['+1 to medical treatment']},
{id:'nv_goggles',name:'Night Vision Goggles',cat:'Utility',special:['Darkvision']},
{id:'smartphone',name:'Smartphone',cat:'Utility',special:['Internet','GPS']},
{id:'utility_belt',name:'Utility Belt',cat:'Utility',desc:'Common gadgets — define contents per scene.',special:[]},
{id:'grappling_hook',name:'Grappling Hook',cat:'Utility',desc:'Climb or swing across one zone.',special:[]},
{id:'rebreather',name:'Rebreather',cat:'Utility',special:['Resist drowning / gas']}
];

// ─── Edit-mode toggles & inline help ──────────────────────
